import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { projects } from '../content/projects.mjs';
import { profile, experience, skillGroups, additionalTools, publications, talks } from '../content/site.mjs';

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const notes = JSON.parse(fs.readFileSync(path.join(root, 'content/original-notes.json'), 'utf8'));
const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]);
const link = (label, href, cls = 'text-link') => '<a class="'+cls+'" href="'+esc(href)+'">'+esc(label)+' <span aria-hidden="true">↗</span></a>';
const button = (l,h,secondary=false) => link(l,h,'button'+(secondary?' button-secondary':''));
const tags = items => '<ul class="tags" aria-label="Methods and tools">'+items.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul>';
const heading = (n,t,d='') => '<div class="section-heading"><div><p class="eyebrow">'+n+'</p><h2>'+t+'</h2></div>'+(d?'<p>'+d+'</p>':'')+'</div>';
const generated = [];
const categories = [...new Set(projects.map(p=>p.category))];

function art(kind='training') {
  const start='<svg viewBox="0 0 520 230" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" focusable="false">';
  if(kind==='geo'){
    let shapes='';
    for(let r=0;r<4;r++) for(let c=0;c<8;c++){
      const x=25+c*65+(r%2)*33,y=22+r*53,opacity=((r*3+c*2)%5)*.12+.12;
      shapes+='<path d="M'+x+','+y+' l28,16 v32 l-28,16 -28,-16 v-32Z" fill="currentColor" fill-opacity="'+opacity+'" stroke="currentColor" stroke-opacity=".3"/>';
    }
    return start+shapes+'<path d="M75 175C140 170 153 52 225 105S350 180 444 63" stroke="white" stroke-width="3" stroke-dasharray="6 7"/><circle cx="225" cy="105" r="7" fill="white"/><circle cx="444" cy="63" r="7" fill="white"/></svg>';
  }
  if(kind==='goals')return start+'<g stroke="currentColor" stroke-opacity=".5" stroke-width="2"><path d="M260 52V112M100 112H420M100 112V152M260 112V152M420 112V152"/></g><rect x="182" y="15" width="156" height="58" rx="12" fill="currentColor" fill-opacity=".18" stroke="currentColor" stroke-opacity=".55"/><text x="260" y="51" text-anchor="middle" fill="currentColor" font-size="16" font-family="sans-serif">Shared objective</text>'+[30,190,350].map((x,i)=>'<rect x="'+x+'" y="152" width="140" height="57" rx="12" fill="currentColor" fill-opacity=".12"/><text x="'+(x+70)+'" y="187" text-anchor="middle" fill="currentColor" font-size="15" font-family="sans-serif">'+['Clarity','Consistency','Alignment'][i]+'</text>').join('')+'</svg>';
  if(kind==='research'){
    let dots='';for(let i=0;i<40;i++)dots+='<circle cx="'+(58+i*10)+'" cy="'+(174-i*2.7+Math.sin(i*5)*27)+'" r="'+(i%4===0?5:3)+'" fill="currentColor" opacity="'+(i%3===0?.9:.4)+'"/>';
    return start+'<path d="M45 25V205H480" stroke="currentColor" opacity=".3"/><path d="M60 180C170 170 230 102 450 61" stroke="currentColor" stroke-width="2"/>'+dots+'<path d="M60 145C170 142 230 74 450 31L450 94C230 131 170 197 60 209Z" fill="currentColor" fill-opacity=".08"/></svg>';
  }
  return start+'<path d="M94 115H440" stroke="currentColor" stroke-opacity=".4" stroke-dasharray="5 6"/>'+[25,195,365].map((x,i)=>'<rect x="'+x+'" y="62" width="130" height="104" rx="16" fill="currentColor" fill-opacity=".12" stroke="currentColor" stroke-opacity=".25"/><circle cx="'+(x+65)+'" cy="97" r="12" stroke="currentColor" stroke-width="2"/><text x="'+(x+65)+'" y="141" text-anchor="middle" fill="currentColor" font-size="16" font-family="sans-serif">'+['Data','Reward','Learning'][i]+'</text>').join('')+'<path d="M428 172C428 221 90 221 90 172" stroke="currentColor" stroke-opacity=".4"/><text x="260" y="218" text-anchor="middle" fill="currentColor" font-size="13" font-family="sans-serif">Evaluate · refine · repeat</text></svg>';
}
function layout(file,title,description,main,{active='',noindex=false}={}){
  const canonical=profile.base+file;
  const nav=[['About','index.html#about'],['Experience','index.html#experience'],['Projects','projects.html'],['Research','research.html'],['Talks','talks.html']];
  const jsonld=file==='index.html'?'<script type="application/ld+json">'+JSON.stringify({'@context':'https://schema.org','@type':'Person',name:profile.name,alternateName:'Polina Tanasevich',url:profile.base,jobTitle:profile.title,sameAs:profile.socials.map(s=>s[1])}).replaceAll('<','\\u003c')+'</script>':'';
  return '<!doctype html>\n<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>'+esc(title)+' | '+esc(profile.name)+'</title><meta name="description" content="'+esc(description)+'"><meta name="theme-color" content="#5424a3">'+(noindex?'<meta name="robots" content="noindex">':'')+'<link rel="canonical" href="'+canonical+'"><meta property="og:type" content="website"><meta property="og:title" content="'+esc(title)+' | '+esc(profile.name)+'"><meta property="og:description" content="'+esc(description)+'"><meta property="og:url" content="'+canonical+'"><meta property="og:image" content="'+profile.base+'assets/png/social-card.png"><link rel="icon" href="assets/svg/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="css/portfolio.css"><script src="index.js" defer></script>'+jsonld+'</head>\n<body><a class="skip-link" href="#main">Skip to content</a><header class="site-header"><div class="header-inner"><a class="brand" href="index.html" aria-label="Polina Kliuchnikova — home"><span class="monogram" aria-hidden="true">pk<span>.</span></span><span>Polina<br><strong>Kliuchnikova</strong></span></a><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="main-nav">Menu <span aria-hidden="true">☰</span></button><nav id="main-nav" class="main-nav" aria-label="Main navigation">'+nav.map(([l,h])=>'<a href="'+h+'"'+(active===l?' aria-current="page"':'')+'>'+l+'</a>').join('')+link('Let’s talk','index.html#contact','nav-contact')+'</nav></div></header><main id="main">'+main+'</main><footer class="site-footer"><div class="wrap footer-main"><div><a class="footer-name" href="index.html">Polina Kliuchnikova<span>.</span></a><p>Machine learning, applied mathematics<br>and the people who work with AI.</p></div><div class="footer-links">'+profile.socials.map(([n,u])=>link(n,u)).join('')+link('Email','mailto:'+profile.email)+'</div></div><div class="wrap footer-bottom"><span>© 2026 Polina Kliuchnikova</span><span>Earlier publications: Polina S. Tanasevich</span>'+link('All projects','projects.html')+'</div></footer></body></html>';
}
function write(file,title,description,body,opts){fs.writeFileSync(path.join(root,file),layout(file,title,description,body,opts).replace(/></g,'>\n<'));generated.push(file);}
function card(p,featured=false){
  const search=[p.title,p.category,p.summary,...p.tools,...p.sections.flatMap(s=>s.paragraphs)].join(' ').toLowerCase();
  return '<article class="project-card'+(featured?' featured-card':'')+'" data-project data-category="'+esc(p.category)+'" data-search="'+esc(search)+'">'+(featured?'<a href="'+p.id+'.html" class="project-visual visual-'+p.visual+'" tabindex="-1" aria-hidden="true">'+art(p.visual)+'</a>':'')+'<div class="card-content"><p class="card-meta">'+esc(p.category)+' <span> / </span> '+esc(p.period)+'</p><h3><a href="'+p.id+'.html">'+esc(p.title)+'</a></h3><p>'+esc(p.summary)+'</p>'+tags(p.tools.slice(0,featured?4:3))+link('Explore project',p.id+'.html')+'</div></article>';
}
function originalNote(key){
  if(!key||!notes[key])return '';
  return '<details class="original-notes" id="original-notes"><summary>Original project notes <span>Detailed reference</span></summary><div class="notes-inner"><p class="note-intro">Preserved from my earlier portfolio for a complete record of the project. These historical notes include the original wording, code sketches and reported measurements, which have not been revalidated here. The edited case study above is the current overview.</p><div class="archival-text" lang="'+(/[а-яё]/i.test(notes[key])?'ru':'en')+'">'+esc(notes[key])+'</div></div></details>';
}
function hero(eyebrow,title,desc,extra=''){return '<section class="page-hero"><div class="wrap"><p class="eyebrow">'+esc(eyebrow)+'</p><h1>'+esc(title)+'</h1><p class="page-intro">'+esc(desc)+'</p>'+extra+'</div></section>';}
function publicationList(items=publications){
  return '<div class="publication-list">'+items.map(p=>'<article class="publication"><div><span class="status status-'+p.status.toLowerCase().replaceAll(' ','-')+'">'+esc(p.status)+'</span><span class="publication-year">'+esc(p.year)+'</span></div><div><h3><a href="'+p.href+'">'+esc(p.title)+'</a></h3><p class="authors">'+esc(p.authors)+'</p><p>'+esc(p.detail)+'</p></div><a class="round-link" href="'+p.href+'" aria-label="Read about '+esc(p.title)+'">↗</a></article>').join('')+'</div>';
}
function talkCard(t){return '<article class="talk-card"><div class="talk-date"><span>'+esc(t.date)+'</span><span class="talk-label">'+esc(t.label)+'</span></div><h3><a href="'+t.id+'.html">'+esc(t.event)+'</a></h3><h4>'+esc(t.title)+'</h4><p>'+esc(t.summary)+'</p>'+link('About the talk',t.id+'.html')+'</article>';}

const home='<section class="hero"><div class="wrap hero-grid"><div class="hero-copy"><p class="eyebrow"><span class="status-dot"></span>'+esc(profile.title)+'</p><h1>Building AI.<br>Understanding<br><em>its behaviour.</em></h1><p class="hero-description">I’m Polina. I work on LLM post-training, evaluation and human–AI interaction, combining hands-on engineering with a background in applied mathematics.</p><div class="button-row">'+button('Explore my work','#projects')+button('Download CV',profile.cv,true)+'</div><div class="hero-affiliations"><span><strong>Huawei</strong> Staff ML Engineer</span><span><strong>ITMO</strong> PhD student · AI & ML</span></div></div><div class="portrait-panel"><div class="portrait-grid" aria-hidden="true"></div><div class="portrait-orbit" aria-hidden="true"></div><span class="portrait-label">ENGINEERING × RESEARCH</span><img class="portrait" src="assets/png/profile2.png" width="400" height="400" alt="Polina Kliuchnikova"><div class="portrait-caption"><span>From mathematical models<br>to working ML systems.</span><span aria-hidden="true">↗</span></div></div></div><div class="wrap hero-bottom"><span>LLM TRAINING & EVALUATION</span><span>HUMAN–AI INTERACTION</span><span>APPLIED MACHINE LEARNING</span></div></section>'+
'<section class="section wrap about-section" id="about"><div><p class="eyebrow">01 / About</p><h2>Research depth.<br>Engineering practice.</h2></div><div class="about-copy"><p class="large-copy">I build and study machine-learning systems, with a particular interest in how they learn from feedback and how people decide to rely on them.</p><p>At Huawei, I work on LLM post-training, model evaluation and retrieval. Previously, I led applied ML work at Sber and developed predictive analytics at VK / MY.GAMES. My earlier work in C++ and computational mechanics gave me a foundation in numerical methods and scientific modelling.</p><p>Alongside engineering, I am a PhD student in AI & Machine Learning at ITMO University. My research covers evaluator reliability, game-theoretic models of human oversight and the identifiability of human preferences.</p><div class="education-strip"><div><strong>ITMO University</strong><span>Doctoral studies · AI & ML · in progress</span></div><div><strong>Lomonosov MSU</strong><span>BSc 2017–2021 · MSc 2021–2023<br>Applied Mathematics</span></div><div><strong>UC Berkeley RDI</strong><span>LLM Agents MOOC · certificate of completion<br>Sep 2024–Jan 2025</span></div></div></div></section>'+
'<section class="section section-tint" id="experience"><span id="job" class="anchor-alias"></span><div class="wrap">'+heading('02 / Experience','From numerical methods<br>to language models.','Research, engineering and technical leadership across different kinds of systems.')+'<div class="experience-list">'+experience.map((e,i)=>'<article class="experience-row"><div class="experience-index">0'+(i+1)+'</div><div class="experience-company"><h3>'+esc(e.company)+'</h3><p>'+esc(e.dates)+'</p></div><div><h4>'+esc(e.role)+'</h4><p>'+esc(e.description)+'</p></div>'+link('Details',e.file)+'</article>').join('')+'</div></div></section>'+
'<section class="section wrap" id="projects">'+heading('03 / Selected projects','A closer look at the work.','Four projects across post-training, geospatial ML, applied LLM systems and feedback research.')+'<div class="featured-grid">'+projects.filter(p=>p.featured).map(p=>card(p,true)).join('')+'</div><div class="catalogue-cta"><div><h3>There’s more to explore.</h3><p>'+projects.length+' projects, with methods, decisions and detailed notes.</p></div>'+button('Browse all projects','projects.html')+'</div></section>'+
'<section class="section section-tint" id="research"><span id="science" class="anchor-alias"></span><div class="wrap">'+heading('04 / Research','How do we learn<br>from human feedback?','Current work on feedback reliability, oversight and the interpretation of human preferences.')+'<div class="research-topics">'+projects.filter(p=>['research-feedback','research-oversight','research-preferences'].includes(p.id)).map(p=>'<a class="topic-card" href="'+p.id+'.html"><span aria-hidden="true">↗</span><h3>'+esc(p.title)+'</h3><p>'+esc(p.summary)+'</p></a>').join('')+'</div>'+publicationList(publications.slice(0,3))+'<div class="section-end">'+link('All research, publications & software','research.html')+'</div></div></section>'+
'<section class="section wrap" id="talks"><span id="conferences" class="anchor-alias"></span>'+heading('05 / Talks','Sharing the work.','Presentations on human–AI interaction, multimodal learning and applied ML.')+'<div class="talk-grid">'+talks.slice(0,3).map(talkCard).join('')+'</div><div class="section-end">'+link('All talks & materials','talks.html')+'</div></section>'+
'<section class="section section-tint" id="skills"><div class="wrap">'+heading('06 / Methods & tools','What I work with.','Methods connected to projects, with the tools used to put them into practice.')+'<div class="skills-grid">'+skillGroups.map(g=>'<article class="skill-card"><h3>'+esc(g.title)+'</h3><p>'+esc(g.description)+'</p>'+tags(g.skills)+link('See it in a project',g.project+'.html')+'</article>').join('')+'</div><details class="additional-tools"><summary>More tools from earlier projects</summary><p>Additional tools used across past research, NLP, analytics and deployment work.</p>'+tags(additionalTools)+'</details></div></section>'+
'<section class="section wrap contact-section" id="contact"><div><p class="eyebrow">07 / Get in touch</p><h2>Let’s talk<br><em>about what’s next.</em></h2><p>I’m happy to discuss ML engineering, research and opportunities to build thoughtful AI systems.</p></div><div class="contact-actions">'+link(profile.email,'mailto:'+profile.email,'email-link')+'<div class="social-row">'+profile.socials.map(([n,u])=>link(n,u)).join('')+'</div>'+button('Download CV',profile.cv,true)+'</div></section>';
write('index.html','ML engineering & research',profile.description,home);

const catalogue=hero('Project catalogue','All the work, in one place.','Explore professional projects, research and independent experiments. Each case includes its context, my contribution, the approach and supporting detail.')+
'<section class="section wrap catalogue-section"><div class="catalogue-controls" data-catalogue-controls hidden><label class="search-label" for="project-search">Find a project or a tool</label><div class="search-row"><input type="search" id="project-search" placeholder="Try RLHF, geo, CatBoost, pricing…" autocomplete="off"><button class="button button-secondary" id="reset-filters" type="button">Reset</button></div><div class="filter-row" role="group" aria-label="Filter projects by area">'+['All',...categories].map((c,i)=>'<button type="button" class="filter-button" data-filter="'+esc(c)+'" aria-pressed="'+(i===0)+'">'+esc(c)+'</button>').join('')+'</div></div><h2 class="sr-only">Project catalogue</h2><p class="result-count" aria-live="polite" aria-atomic="true" id="result-count">'+projects.length+' projects</p><div class="project-grid">'+projects.map(p=>card(p)).join('')+'</div><div class="empty-state" id="empty-state" hidden><h2>No matching projects</h2><p>Try another term or reset the filters to see the full catalogue.</p></div><noscript><p>All projects are shown above. Use your browser’s Find command to look for a topic.</p></noscript></section>';
write('projects.html','All projects','Explore all projects by Polina Kliuchnikova: Huawei, Sber, VK / MY.GAMES, research and independent work.',catalogue,{active:'Projects'});

for(const p of projects){
 const body=hero(p.category+' / '+p.period,p.title,p.summary,'<div class="button-row">'+button('All projects','projects.html',true)+(p.links||[]).map(([l,h])=>button(l,h,true)).join('')+'</div>')+
 '<div class="wrap case-layout"><aside class="case-sidebar"><p class="eyebrow">Project at a glance</p><dl><dt>Context</dt><dd>'+esc(p.category)+'</dd><dt>My role</dt><dd>'+esc(p.role)+'</dd><dt>Period</dt><dd>'+esc(p.period)+'</dd></dl><h2 class="sidebar-title">Methods & tools</h2>'+tags(p.tools)+'<nav aria-label="On this page"><h2 class="sidebar-title">In this case</h2>'+p.sections.map((s,i)=>'<a href="#section-'+i+'">'+esc(s.title)+'</a>').join('')+(p.note?'<a href="#original-notes">Original notes</a>':'')+'</nav><button class="print-button" type="button" data-print hidden>Print / save as PDF</button></aside><article class="case-body">'+
 (p.media?'<figure class="case-media"><img src="'+p.media+'" alt="Simulation of the metamaterial structure" loading="lazy">'+(p.video?'<video controls preload="none" poster="'+p.media+'" aria-label="Metamaterial simulation"><source src="'+p.video+'" type="video/mp4">Your browser does not support inline video.</video>':'')+'</figure>':'')+
 p.sections.map((s,i)=>'<section class="case-section" id="section-'+i+'"><h2>'+esc(s.title)+'</h2>'+s.paragraphs.map(x=>'<p>'+esc(x)+'</p>').join('')+'</section>').join('')+originalNote(p.note)+'<div class="case-bottom">'+link('Back to all projects','projects.html')+link('Contact me','index.html#contact')+'</div></article></div>';
 write(p.id+'.html',p.title,p.summary,body,{active:p.category==='Research'?'Research':'Projects'});
}
for(const e of experience){
 const relevant=e.category?projects.filter(p=>p.category===e.category):e.company==='CAE Fidesys'?projects.filter(p=>['patent-1','patent-2'].includes(p.id)):e.company==='Lomonosov MSU'?projects.filter(p=>['science-1','tomsk_2023','megagrant','materials-startup'].includes(p.id)):[];
 const body=hero(e.dates+' / Experience',e.company+' · '+e.role,e.description)+'<section class="section wrap"><div class="role-intro"><h2>'+esc(e.intro)+'</h2><ul class="role-highlights">'+e.highlights.map(h=>'<li>'+esc(h)+'</li>').join('')+'</ul></div>'+
 (relevant.length?'<div class="section-heading"><h2>Projects & contributions</h2><p>'+relevant.length+' detailed case studies</p></div><div class="project-grid">'+relevant.map(p=>card(p)).join('')+'</div>':'<div class="reading-width"><h2>Teaching approach</h2><p>I combined structured practice with individual feedback, helping students understand why a method works and when to use it. Teaching strengthened my ability to explain technical concepts, adapt to different levels of preparation and support a learner’s progress.</p><p>That experience continues to inform how I mentor colleagues and communicate mathematical or machine-learning ideas.</p></div>')+
 '<div class="section-end">'+link('All experience','index.html#experience')+' '+link('Full project catalogue','projects.html')+'</div></section>';
 write(e.file,e.company+' experience',e.description,body,{active:'Experience'});
}
write('research.html','Research & publications','Research in human–AI interaction, feedback reliability, game theory and numerical modelling.',
 hero('Research & publications','Feedback, decisions and the mathematics behind them.','My research connects applied mathematics with the study of language models and human–AI interaction.')+
 '<section class="section wrap"><div class="section-heading"><h2>Current research</h2><p>Doctoral studies in AI & Machine Learning at ITMO University.</p></div><div class="project-grid">'+projects.filter(p=>p.id.startsWith('research-')).map(p=>card(p)).join('')+'</div></section>'+
 '<section class="section section-tint"><div class="wrap">'+heading('Publications','Papers & manuscripts.','Explore my publication record on Google Scholar. Earlier work appears under Polina S. Tanasevich.')+button('View publications on Google Scholar',profile.socials[2][1])+'</div></section>'+
 '<section class="section wrap">'+heading('Mathematical foundations','Numerical methods & registered software.','Computational mechanics, inverse problems and heterogeneous materials. Publications and software registrations are collected in my ISTINA profile.')+button('View research & software on ISTINA',profile.socials[3][1],true)+'</section>',{active:'Research'});
write('talks.html','Talks & conference materials','Conference presentations on AI, machine learning, human–AI interaction and applied mathematics.',hero('Talks & conference materials','Research is a conversation.','Presentations, recordings and slides across machine learning, cognitive science and computational mechanics.')+'<section class="section wrap"><h2 class="sr-only">Presentations</h2><div class="talk-grid">'+talks.map(talkCard).join('')+'</div></section>',{active:'Talks'});
for(const t of talks){
 const buttons=[t.video&&['Watch recording',t.video],t.slides&&['View slides',t.slides],...t.sources].filter(Boolean);
 const body=hero(t.event,t.title,t.summary,'<p class="event-meta">'+esc(t.date)+' · '+esc(t.location)+'</p><div class="button-row">'+buttons.map(([l,h],i)=>button(l,h,i>0)).join('')+'</div>')+
 '<section class="section wrap talk-detail"><div class="reading-width"><h2>About the presentation</h2>'+t.paragraphs.map(p=>'<p>'+esc(p)+'</p>').join('')+(t.originalTitle?'<details class="original-title"><summary>Original talk title</summary><p lang="ru">'+esc(t.originalTitle)+'</p></details>':'')+originalNote(t.note)+'</div>'+
 (t.image?'<figure class="talk-image"><img src="'+t.image+'" alt="'+esc(t.event)+' presentation visual" loading="lazy"></figure>':'')+'</section><section class="section section-tint"><div class="wrap"><h2 class="related-heading">Explore the related work</h2><div class="project-grid">'+projects.filter(p=>t.related.includes(p.id)).map(p=>card(p)).join('')+'</div><div class="section-end">'+link('All talks','talks.html')+'</div></div></section>';
 write(t.id+'.html',t.event,t.summary,body,{active:'Talks'});
}
write('project-3.html','Project catalogue','Explore the full project catalogue.',hero('Project catalogue','Looking for a project?','All professional projects, research and independent experiments are collected in one place.',button('Browse all projects','projects.html')),{noindex:true});
write('404.html','Page not found','Find the project, presentation or research you were looking for.',hero('404','Let’s find the right page.','This address is no longer available. Explore the catalogue or return to the homepage.',button('All projects','projects.html')+' '+button('Home','index.html',true)),{noindex:true});
fs.writeFileSync(path.join(root,'assets/jpeg/patent-1.html'),'<!doctype html><html lang="en"><meta charset="utf-8"><meta name="robots" content="noindex"><meta http-equiv="refresh" content="0;url=../../patent-1.html"><title>Software registration</title><a href="../../patent-1.html">View the software registration case study</a></html>');
fs.writeFileSync(path.join(root,'sitemap.xml'),'<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+generated.filter(f=>!['404.html','project-3.html'].includes(f)).map(f=>'<url><loc>'+profile.base+f+'</loc><lastmod>'+profile.updated+'</lastmod></url>').join('')+'</urlset>\n');
fs.writeFileSync(path.join(root,'.nojekyll'),'');
console.log('Built '+generated.length+' pages: '+projects.length+' projects, '+talks.length+' talks and '+experience.length+' experience pages.');
